### ISSUE TITLE
deploy-github should should allow Draft Release title to be configurable

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#103]
e.g. if the workspace name is `graknlabs_grakn_core`, the draft title should be `Grakn Core`

**Comment by vmax** [comment]
@lolski if we want to make it reusable by other people, how do we parse organization vs repo name only using workspace name?

**Comment by haikalpribadi** [comment]
let's have the rule take in title `string` as an argument, and append the version to it at the end. For example:

```
deploy_github(
    name = "deploy-github",
    title = "Grakn Core",
    title_append_version = true,
    ...
)
```

**Comment by haikalpribadi** [comment]
`title_append_version` default should be `FALSE`
