### ISSUE TITLE
assemble_versioned should version distributions by simply modifying the content of the archive

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#105]
right now in order to add version, it needs to rebuild a new zip from an existing zip and takes a long time .

**Comment by vmax** [comment]
@lolski what do you mean by
>rebuild a new zip from an existing zip

AFAIU, `assemble_versioned` takes `zip`+`VERSION` and produces `zip` — could you elaborate on what is there to optimize?

**Comment by lolski** [comment]
If we can just modify the input archives that would be more efficient, right now we have to wait for a long time since rebuilding 9 archives take a long time

**Comment by vmax** [comment]
@lolski [ref](https://stackoverflow.com/a/25739108/4617642)
>Updating a file in a ZIP is not supported. You need to rebuild a new archive without the file, then add the updated version.

**Comment by vmax** [comment]
I'm closing this due to technical impossibility to do what is described in the issue. Please open a new one with another approach.
