### ISSUE TITLE
deploy-github script should be runnable without bazel

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/bazel-distribution#108]
So that `@graknlabs_workbase` can use the script from CI too

**Comment by vmax** [comment]
@haikalpribadi `deploy-github` depends on having `ghr` at certain location which is put there by `bazel`. Should we download it manually on its absence in order to support this workflow?

**Comment by haikalpribadi** [comment]
I'm not quite I remember the full context of this issue from when I wrote it. On one hand, we shouldn't hack our current `deploy-github` to work for workbase which is "temporarily" not built with Bazel. On the other hand, I see the value on being able to call `deploy-github` for workbase. Could there perhaps be a way for us to call `deploy-github` through bazel, without building workbase with bazel?

**Comment by vmax** [comment]
@haikalpribadi we could write `BUILD` file which has `exports_file([])` *after* building distributions. This way they won't be generated in `bazel` but `deploy-github` will have access to them.

**Comment by haikalpribadi** [comment]
let's find time to discuss this at some point this week, remind me @vmax. I don't quite see it yet, but we can hash out with some examples. cc: @lolski

**Comment by haikalpribadi** [comment]
Basically, the `deploy-github` should be usable by two scenarios:

Option 1: when the repo is BUILT with Bazel:
```
bazel run //:deploy-github -- $CIRCLE_SHA1
```

Option 2 (when the repo is NOT BUILT with Bazel):
```
bazel run //:deploy-github -- $CIRCLE_SHA1 -a ./path/to/distribution/archives/
```
