### ISSUE TITLE
java_deps - The JARs produced by two Bazel targets from different packages but with the same label may overwrite each other

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#111]
The following example demonstrates how the JARs from `//bootup:library` and `//server:library` may overwrite each other because they both produce a JAR with an identical name `liblibrary.jar`.

```
java_library(
    name = "server",
    runtime_deps = [
        "//bootup:library",
        "//server:library",
    ]
)

java_deps(
    name = "server-deps",
    target = ":server",
    java_deps_root = "server/services/lib/",
    version_file = "//:VERSION",
    visibility = ["//:__pkg__"]
)

assemble_zip(
    name = "assemble-mac-zip",
    targets = ["//:all-deps"],
)
```

The proposed solution: use the Bazel package name as a way to create namespace: `bootup-liblibrary.jar` and `server-liblibrary.jar`

**Comment by vmax** [comment]
Not addressed yet: what if `//daemon` and `//daemon` are from different workspaces?

**Comment by lolski** [comment]
In the discussion between me and @vmax, we propose the following alternatives:

- add the workspace name as well such that `"@graknlabs_grakn_core//daemon:daemon` produce a JAR `graknlabs_grakn_core_daemon_daemon.jar` and `//daemon:daemon` produces `daemon_daemon.jar`
- detect for duplicates and dedupilcate them, eg., if there are two `daemon.jar`s, produce `daemon_1.jar` and `daemon_2.jar`
- always use maven coordinates for every `java_library` target so maintaining name uniqueness is the responsibility of the user
