### ISSUE TITLE
Output names of assemble-maven and deploy-maven artifacts/jars

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/bazel-distribution#112]
Did we ever have a discussion on how we should name the output filename of the maven artifacts of `assemble-maven` jars? I feel like we have, but I can't find the issue that documents it.

At the moment, if you run (e.g. for Graql) `bazel build //java:assemble-maven`, the output will be `bazel-bin/java/io.graql:lang.jar`. This is problematic because for example on Mac, the colon `:` will be replaced with `/` (which itself is problematic as it confuses with directories).

Once we call `deploy-maven`, what we see on repo.grakn.ai is that the artifacts are named `artifactid-X.YZ.jar`, which misses the `groupid` to make the jar name globally unique and complete.

To solve both problems for `assemble-maven` and `deploy-maven`, I suggest we name the jars such that:
- we replace `.` and `:` with `-`
- `assemble-maven` should output `group-id-artifact-id.jar`
- `deploy-maven` should upload `group-id-artifact-id-X.Y.Z.jar`

**Comment by vmax** [comment]
@haikalpribadi AFAIR Nexus doesn't preserve the filename of the file you upload and structures directories/files according to repository format. So, we only need to resolve it for `assemble_maven`

**Comment by haikalpribadi** [comment]
Can we configure Nexus to set a more detailed name, @vmax ? As I predicted it would be an issue for users, for example, here: https://github.com/graknlabs/grakn/issues/5127

**Comment by vmax** [comment]
@haikalpribadi It is not possible because Nexus just follows Maven conventions, [ref](https://stackoverflow.com/a/13371622/4617642)

**Comment by haikalpribadi** [comment]
Then how do we resolve the issue in https://github.com/graknlabs/grakn/issues/5127, @vmax ? And how do the other artifacts produce a name that is unique in maven repos?

**Comment by vmax** [comment]
@haikalpribadi general convention seems to be including the identifier into `artifactId`, i.e. [search for `api` in Maven Central](https://mvnrepository.com/search?q=api) returns (filenames):
- `slf4j-api-1.8.0-beta4.jar`
- `javax.servlet-api-4.0.1.jar`
- `jaxb-api-2.4.0-b180830.0359.jar`

Same way, the issue you linked could be resolved by renaming:
- `io.grakn.client:api` → `io.grakn.client:grakn-client-api`
- `io.grakn.core:api` → `io.grakn.core:grakn-core-api`

**Comment by haikalpribadi** [comment]
Yes, but still not the full `group-id` + `artifact-id` used as the aftifact name. For example: `org.apache.logging.log4j » log4j-api`

It would be very ugly to do it this way. Is there no other way?

**Comment by vmax** [comment]
@haikalpribadi speaking of renaming artifacts in the repo itself, there isn't. However, client could rename JARs as they wish as long as they're in classpath of the running app.

**Comment by haikalpribadi** [comment]
I'll rename all our Maven ArtifactID to be unique.
