### ISSUE TITLE
Every rule should have a consistent style that is intuitive for users

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#118]

**Comment by vmax** [comment]
@lolski could we take time [preferably, this week] to identify inconsistencies in rules [if any] so that we know what to work on to fix this issue?

**Comment by vmax** [comment]
I feel rules are used quite consistently now. It may not be _intuitive_ since we lack proper user-facing documentation, but IMO that is a separate issue that needs consideration. Let's try creating a more descriptive issues from now on 🙂
