### ISSUE TITLE
The `additional_files` parameter of `distribution` should be able to accept directories and bazel targets, not just files

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#14]
The `additional_files` parameter of `distribution` should be able to accept a directory. For example, given the following directory structure:

```
runner/conf
runner/conf/web_content
runner/conf/web_content/web_content_schema.gql
runner/conf/societal_model
runner/conf/societal_model/societal_model.gql
```

We should be able to include them in the distribution without having to specify each file one by one:
```
distribution(
    name = "distribution",
    ...
    additional_files = {
        "//runner:conf": 'conf',
    },
)

```

**Comment by vmax** [comment]
@lolski despite executing correctly (checked locally on [`bazelbuild/bazel-buildfarm`](https://github.com/bazelbuild/bazel-buildfarm)), building `genrule` targets with directories is not recommended:

`WARNING: /Users/vmax/work/GraknLabs/temp/BUILD:1:1: input 'ins' to //:qqq is a directory; dependency checking of directories is unsound`

**Comment by lolski** [comment]
@vmax good point! how about if we support `glob` instead of directories?
```
distribution(
    name = "distribution",
    ...
    additional_files = {
        'conf': glob(["//runner:conf/**"])
    },
)
```
Assigning it to myself as I'm currently working on it.

**Comment by vmax** [comment]
@lolski this is better (`glob` is representing a list of files), but keep in mind that this will prevent you from having `BUILD` files inside directories (those are skipped by `glob`)

**Comment by lolski** [comment]
Closing it as it's not relevant anymore because there's no immediate requirement to accept directories and bazel targets in the `additional_files` field of `distribution` (FYI, the rule itself has also been restructured into multiple rules such as `assemble_*`).
