### ISSUE TITLE
Allow properties to also be provided as arguments to deploy rules

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/bazel-distribution#146]
Right now, we create a file (`deployment.properties`) in every repo to hold two properties:
```
repo.github.organisation=graknlabs
repo.github.repository=grakn
```

These properties are not used anywhere else other than for `deploy_github`. Given that there are only 2 properties that need to be defined in ever repo's `deployment.properties` file, and that these 2 properties are uniquely used for `deploy_github`, we should just add them as arguments to the `deploy_github` rule. It reduces one more config file on the repo's root directory.

EDIT:

Other properties (e.g. those written in `@graknlabs_build_tools//deployment.properties`) not be that reusable/repeatable. Any of them can face the use case such as the above. We should make it optional for every `delpoy_*` rule to provide the arguments directly in rule declaration in the `BUILD` file. It would be "nice to have" (i.e. no need to declare `deployment.properties` file in every repo.

**Comment by haikalpribadi** [comment]
Oh wait, would this make `deploy_github` inconsistent to the other `deploy_*` rules, @vmax ? Are the other properties in the `deployment.properties` file in `@graknlabs_build_tools` actually repeatedly reused between different/multiple targets? cc: @lolski

**Comment by lolski** [comment]
Hmm yes, it would make it less consistent.

The other properties can be reused by other `deploy_*` rules because they all deploy to `repo.grakn.ai`.

**Comment by haikalpribadi** [comment]
Right, @lolski. Then I should deprioritise (and change) this issue. If we want to make the above properties to be arguments, we should make it as an optional alternative for every `deploy_*` rule. Let's not prioritise this issue for the current "wrapping-up" of CI work, @vmax. I will now modify the description.

**Comment by vmax** [comment]
Given we're quite happy with current setup and using `deployment.properties`, let's stick to using it. If need ever arises [e.g. someone from community has a request or we identify why it should be done], let's open a new issue.
