### ISSUE TITLE
The 'distribution' rule should be named 'java_distribution'

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#21]
The rule specifies `targets` which has to be a `java_library()` and can't be anything else. This means you can't build other kinds of distribution (eg., a Python distribution) with it. Therefore it's better if we rename the rule to be more explicit

**Comment by vmax** [comment]
We now have:
* `distribution_zip` — you're not limited in what you pass in `distribution_structures` (it accepts `.tgz` layers)
* `distribution_structure` — which is indeed currently limited to Java — but we're renaming it anyway in #27
