### ISSUE TITLE
Supporting Targets with No .Srcjar

### ISSUE THREAD

**Issue by amit-traiana** [graknlabs/bazel-distribution#214]
I'm using `assemble-maven` in a Scala project. [scala_library ](https://github.com/bazelbuild/rules_scala/blob/master/docs/scala_library.md) is implemented differently to `java_library` so the above if condition will not trigger:

https://github.com/graknlabs/build-tools/blob/master/distribution/maven/rules.bzl#L270-L277

So the first thing will be support `scala-rules` if possible, because both are very similar (use POM, Jar file, srcjar etc) and Scala users can also benefits from `assemble-maven`.

Second issue, that if the `target` is not of type `java`, it will revert into the second option in the if statement. The 2nd if statement never defines `srcjar` like the first option, so the Depset will fail to populate because the variable was never created. 

Thanks!

**Comment by vmax** [comment]
Fixed by #217
