### ISSUE TITLE
Unique POM File Name

### ISSUE THREAD

**Issue by amit-traiana** [graknlabs/bazel-distribution#215]
I own a project where a single BUILD file will define two `java_library` targets. At the moment, `build-tools` always use hard-coded POM file named `pom.xml`. So if I'm running both targets, the first `pom.xml` will get overwrited by the second. I created a fork that names the pom file based on the target name (`my_target_pom.xml` for example). 

This solve the issue but create another one - `deploy_maven` is correctly coupled into `assemble-maven` - it will look for that statically named pom file named `pom.xml`. `deploy_maven` support passing the `assemble-maven` target as optional argument which solve this issue, but it means this argument must be a must and not optional (which makes sense to me - as there is already sort of a coupling between the two with the static pom file name).

Let me know if that works for you, and if so - I'll send a pull-request.

Thanks!

**Comment by amitz** [comment]
#216

**Comment by vmax** [comment]
Fixed by #217
