### ISSUE TITLE
feature-request: add android_library support to maven distribution

### ISSUE THREAD

**Issue by jagobagascon** [graknlabs/bazel-distribution#233]
I'm trying to deploy an `android_library` to maven, but maven assemble and deployment rules only work with jars, and I need to upload an `aar` artifact.

I tried modifying the rules myself to make a PR ~~but for some reason aspects are not working when I define the `aar` as target (and thus pom generation fails). I think [it may be a bug](https://github.com/bazelbuild/bazel/issues/11545) with Bazel or the Android rules~~ but I couldn't make it work without having to completely change the deployment rule. 

The `aar` artifact is an implicit output of the `android_library` rule, which means it's just a file and aspects do not work on them.

```python
assemble_maven(
    name = 'assemble',
    target = ':my_android_lib',
)
assemble_maven(
    name = 'assemble',
    target = ':my_android_lib.aar', # fails because aspects are not executed
)
```

To make it work I had to modify the deployment so I could generate the pom and then explicitly choose the deployed file:
```python
assemble_maven(
    name = 'generate_pom',
    target = ':build',
)
publish_maven(
    name = 'publish',
    pom_file = ':generate_pom',
    target = ':build.aar',
    sources = ':build.srcjar',
)
```

Are there any plans on supporting Android `aar` files?

**Comment by lolski** [comment]
Hi! Unfortunately, we have no plans for that in the foreseeable future (we're not building Android products as a company).

What you can do instead is to create your own distribution repository, and it can depend on this repository if you feel that you can build it on top of existing functionalities which we provide.

Closing this issue for now.

**Comment by cpsauer** [comment]
@jagobagascon, did you end up solving this another way? Was looking into doing the same :)

**Comment by jagobagascon** [comment]
@cpsauer I ended up writing my own Bazel rule. As I say in my first comment, I had to split the deployment in two: pom generation and the deployment itself.

The rule to create the `pom.xml` does just the same as this library (using the Android library we can get the dependencies to generate the pom) and the deployment rule has a `target` field to define the deployed file. It just calls `mvn deploy:deploy-file` with the generated pom and the aar file I want to deploy.

```python
# generate pom
generate_pom(
    name = 'generate_pom',
    target = ':my_android_lib', # android_library (only used to generate the pom)
    project_url = project_url,
    project_name = 'my_android_lib',
    packaging = 'aar',
)

# publish calling `bazel run :publish --define version=1.2.3`
publish_to_artifactory(
    name = 'publish',
    pom_file = ':generate_pom',
    target = ':my_android_lib.aar', # deployed artifact
    sources = ':libmy_android_lib-src.jar',
    url = deployment_url,
    requires_auth = True,
    user = GITHUB_ACTOR,
    password = GITHUB_TOKEN,
)
```

Our repo is not currently public but you can take a look at the relevant Bazel code here: https://gist.github.com/jagobagascon/4e9499eaf69934f14578d3677afc3539

**Comment by cpsauer** [comment]
Thanks so much @jagobagascon!

I (and everyone else who comes across this in the future) really appreciate it.

**Comment by cpsauer** [comment]
@jagobagascon, you didn't also solve the issue of bundling up the transitive deps (minus maven deps) into the aar, by any chance, did you? Was tackling that full on and it looks a bit...gnarly.

**Comment by jagobagascon** [comment]
I have a bunch of `android_library`s that depend on each other but all of them are deployed with maven, so I didn't need to include any transitive deps.
