### ISSUE TITLE
assemble_maven should produce one aggregated Maven Artifact from multiple Bazel packages

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#243]
We need the `assemble_maven` rule to produce just one Maven Artifact from multiple Bazel packages. Consider our repositories: `@graknlabs_common`, `@graknlabs_graql`, `@graknlabs_client_java`. Each of them has many Bazel packages, but each repository is depended by our users as one Maven Artifact. By not producing one Maven Artifact, we make it annoying for our users to depend on our repositories, as they have to declare 5+ artifacts to depend on in their `pom.xml`.

To produce one artifact, `assemble_maven` should just traverse the dependency graph and collect the content of every package to be merged into one artifact, until either 1 of two things happens:
a) you hit another target of our own code, that has it's own maven_coordinates
b) you hit an external target which is a 3rd party dependency. 
In both cases above we add their maven coordinates into the generated `pom.xml` for the aggregated artifact.

**Comment by flyingsilverfin** [comment]
Further, we also want to be able to create a bazel library that includes multiple packages as one package that can be depended on as source - for example, currently, in Graql (for 2.0) there are 6 packages instead of 1. This means everywhere that `graql` was depended on now means 6 libraries may have to be depended on, which is awkward.

If we could, similarly to the `assemble_maven` issue above, package a single library that can be released as `assemble_maven` made of the same sources or the sub-packages directly

**Comment by flyingsilverfin** [comment]
Another instance of this is in `grabl-tracing` -- we don't need to deploy two artifacts (one for tracing proto, and separately the client), we only need to deploy the grabl-client with the protocol bundled in it

**Comment by haikalpribadi** [comment]
> Further, we also want to be able to create a bazel library that includes multiple packages as one package that can be depended on as source - for example, currently, in Graql (for 2.0) there are 6 packages instead of 1. This means everywhere that `graql` was depended on now means 6 libraries may have to be depended on, which is awkward.
> 
> If we could, similarly to the `assemble_maven` issue above, package a single library that can be released as `assemble_maven` made of the same sources or the sub-packages directly

Do you mean we should create an alternative to `java_library` that allows us to depend on multiple Bazel packages at the same time, @flyingsilverfin ? So that we don't need to depend on Graql sub packages one at a time in our own Grakn Labs repos?

Is this even possible, @vmax ?

**Comment by lolski** [comment]
Let's assess if `rules_jvm_external` supports our needs out of the box. The [docs](https://github.com/bazelbuild/rules_jvm_external#publishing-to-external-repositories) (under section "Publishing to External Repositories") says that the rule supports assembling and deploying Maven artifacts.

The benefit would be that we can streamline our Maven rules greatly, since our implementation have started to become quite complex.

**Comment by vmax** [comment]
Addressed by #292
