### ISSUE TITLE
Rename graknlabs/deployment repository to graknlabs/bazel-distribution

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/bazel-distribution#32]
We should rename this repository to `bazel-distribution` and update all graknlabs' dependency to this repo. Once ready, share it on `https://github.com/jin/awesome-bazel`.

**Comment by haikalpribadi** [comment]
What's the estimated effort on adding simple tests for this repo before sharing it with the community, @vmax @lolski ? It would be useful to have them before we accept any PRs from the community.

**Comment by vmax** [comment]
@haikalpribadi what kind of tests did you have in mind? end-to-end?

**Comment by vmax** [comment]
@haikalpribadi could you or @lolski rename the repo (I lack the needed permissions) ? it will **not** break existing integrations

**Comment by haikalpribadi** [comment]
> what kind of tests did you have in mind? end-to-end?
What are your thoughts on this, @lolski ?

**Comment by vmax** [comment]
@haikalpribadi @lolski we renamed the repo. should we have a discussion // separate issue on the matter of deployment testing?
