### ISSUE TITLE
Create README.md that documents how to use the tools in this repository (generically)

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/bazel-distribution#33]
We should write documentation for this repo, in the README.md so everyone can immediately see it. We should make sure it's functional generically, so other developers other than our Grakn team can use them, but wherever there need to be examples, use Grakn as an example so it's easy for us.

**Comment by vmax** [comment]
@haikalpribadi @lolski WDYT of looking into using [`bazelbuild/skydoc`](https://github.com/bazelbuild/skydoc) for it?
