### ISSUE TITLE
deploy_pip should have a `deps` attribute which allows user to supply dependencies

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#34]
`deploy_pip` expects a certain set of dependencies to be available. these dependencies should be supplied externally by the user of `deploy_pip` rather than internally to avoid a hard-to-find dependency clash situation.

Imagine a scenario where the application happens to depend `pkglib` version `3.0` and what `deploy_pip` needs is `pkglib` version `1.1`. There's a high chance that a dependency clash will happen and when they do it will happen in a way that's hidden from the user, since he/she doesn't see that `deploy_pip` imports `pkglib` internally.

**Comment by vmax** [comment]
Fixed by #35
