### ISSUE TITLE
Split deploy_pip, deploy_npm, and deploy_jar

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#43]
`deploy_pip`, `deploy_npm`, and `deploy_jar` both builds and deploys the distribution. Each of them needs to be split into a rule which build the distribution (`distribution_pip`) and deploy the distribution (`deploy_pip`)

**Comment by vmax** [comment]
Replaced by #44, #58, #59
Let's have bite-size issues instead of umbrella ones 🙂
