### ISSUE TITLE
deployment_rules_builder.py should not take deployment.properties twice

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#80]

**Comment by vmax** [comment]
@lolski let's have a look at actual invocation of `deployment_rules_builder.py` [got from `bazel build -s //distribution/maven:rules`]:

```
external/graknlabs_bazel_distribution/maven/deployment_rules_builder.py \
external/graknlabs_bazel_distribution/maven/templates/rules.bzl \ # rules_template_fn
bazel-out/darwin-fastbuild/bin/distribution/maven/rules.bzl \ # rules_output
external/graknlabs_build_tools/deployment.properties \ # deployment_properties_fn
@graknlabs_build_tools//:deployment.properties'  # deployment_properties_lbl
```

Last two arguments which have seemingly same values have very different purpose.
- `deployment_properties_fn` is the filename (*path*) of properties file, from which we read `{maven_packages}` property
- `deployment_properties_placeholder` is the Bazel label (*string*) of properties file that would be used as default in external `deploy_maven` targets

My suggestion would be to refactor `deployment_rules_builder` slightly to use `argparse` and to specify arguments like this:
```
deployment_rules_builder.py --template $rules_template_fn ---output $rules_template_fn --properties $deployment_properties_fn --properties_label $deployment_properties_lbl
```

**Comment by vmax** [comment]
After discussion with @lolski we decided that existing usage is already clear to user and does not need more improvement.
