### ISSUE TITLE
deploy_github should fail with non-zero exit code if unable to create a draft release

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#86]
Currently, `deploy_github` returns with exit code 0 even when it was unable to create a draft.

Below is an excerpt from this job indicating the aforementioned behavior: https://circleci.com/gh/lolski/graql/149
```
$ bazel run //java:deploy-github-zip -- ${GRABL_CREDENTIAL}

==> Create a draft release
Failed to create GitHub release page: failed to create a release: POST https://api.github.com/repos/lolski/graql/releases: 404 Not Found []
```

**Comment by vmax** [comment]
@lolski do we need to report it to [tcnksm/ghr](https://github.com/tcnksm/ghr/issues)?

**Comment by vmax** [comment]
@lolski I've checked and they actually exit with correct code [in upstream](https://github.com/tcnksm/ghr/blob/master/cli.go#L294-L295). However, we were ignoring that error code
