### ISSUE TITLE
Rules should verify that every environment variable that it uses are defined before anything else

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#92]
And some of them aren't defined, return a helpful error message:
```
$ bazel run //:deploy-brew
Error - The following environment variables needs to be set / can't be empty: $GRABL_CREDENTIAL, $CIRCLE_SHA1
```

**Comment by vmax** [comment]
I've checked all deployment rules and they all check for presence of environment variables that they require. If you discover it to not be the case, please open a new issue describing a *specific* rule and variable that it requires but does not check.
